<a href="https://colab.research.google.com/github/queziamirandaDev/BackEnd-com-Nodejs/blob/main/08_analise_explloratoria.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# biblioteca de manipulação

import pandas as pd

In [2]:
df_vendas = pd.read_csv('base_vendas.csv')

df_vendas.head()

,matricula_funcionario,Nome Funcionario,Cargo,codigo_loja,nome_loja,codigo_produto,descricao_produto,Categoria,preco_custo,valor_unitario,quantidade,comissao,dt_venda,dt_entrega
0,123456111,José Maria,Vendedor,CL001,Loja Matriz,10013,Fogão,Eletrodomésticos,"210,9","404,1",1,NaN,28/09/2020 16:19,05/10/2020 16:31
1,123456111,José Maria,Vendedor,CL001,Loja Matriz,10018,Colchão,Casa,"109,9","249,9",1,NaN,07/03/2020 12:47,08/03/2020 12:47
2,123456111,José Maria,Vendedor,CL001,Loja Matriz,10014,Geladeira,Eletrodomésticos,"699,9","1346,9",1,NaN,21/04/2019 10:48,23/04/2019 15:55
3,123456111,José Maria,Vendedor,CL001,Loja Matriz,10001,Smartphone,Eletrônicos,"899,9","1676,9",1,NaN,07/05/2020 17:59,08/05/2020 14:31
4,123456111,José Maria,Vendedor,CL001,Loja Matriz,10004,Máquina Lavar Roupa,Eletrodomésticos,1099,"1709,1",1,"0,05",14/08/2019 16:56,19/08/2019 15:52

In [3]:
# colunas do DataFrame
df_vendas.columns

Index(['matricula_funcionario', 'Nome Funcionario', 'Cargo', 'codigo_loja',
       'nome_loja', 'codigo_produto', 'descricao_produto', 'Categoria',
       'preco_custo', 'valor_unitario', 'quantidade', 'comissao', 'dt_venda',
       'dt_entrega'],
      dtype='object')

In [4]:
# numero de linhas e colunas do DataFrame
df_vendas.shape

(3000, 14)

In [5]:
df_vendas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   matricula_funcionario  3000 non-null   int64
 1   Nome Funcionario       3000 non-null   object
 2   Cargo                  3000 non-null   object
 3   codigo_loja            3000 non-null   object
 4   nome_loja              3000 non-null   object
 5   codigo_produto         3000 non-null   int64
 6   descricao_produto      3000 non-null   object
 7   Categoria              3000 non-null   object
 8   preco_custo            3000 non-null   object
 9   valor_unitario         3000 non-null   object
 10  quantidade             3000 non-null   int64
 11  comissao               159 non-null    object
 12  dt_venda               3000 non-null   object
 13  dt_entrega             3000 non-null   object
dtypes: int64(3), object(11)
memory usage: 328.3+ KB

In [7]:
df_vendas.describe().round(2)

       matricula_funcionario  codigo_produto  quantidade
count           3.000000e+03         3000.00     3000.00
mean            1.234567e+08        10010.47        2.45
std             3.490000e+02            5.77        1.11
min             1.234561e+08        10001.00        1.00
25%             1.234563e+08        10006.00        1.00
50%             1.234567e+08        10011.00        2.00
75%             1.234570e+08        10015.00        3.00
max             1.234571e+08        10020.00        4.00

In [8]:
df_vendas.describe(include='object')

,Nome Funcionario,Cargo,codigo_loja,nome_loja,descricao_produto,Categoria,preco_custo,valor_unitario,comissao,dt_venda,dt_entrega
count,3000,3000,3000,3000,3000,3000,3000,3000,159,3000,3000
unique,12,1,4,4,20,4,20,19,4,2994,2989
top,José Maria,Vendedor,CL001,Loja Matriz,Aspirador de pó,Casa,"88,9","189,9","0,05",09/07/2019 16:05,09/12/2019 10:12
freq,280,3000,793,793,173,907,173,316,49,2,2

In [9]:
df_vendas.describe(include='all')

,matricula_funcionario,Nome Funcionario,Cargo,codigo_loja,nome_loja,codigo_produto,descricao_produto,Categoria,preco_custo,valor_unitario,quantidade,comissao,dt_venda,dt_entrega
count,3.000000e+03,3000,3000,3000,3000,3000.000000,3000,3000,3000,3000,3000.000000,159,3000,3000
unique,NaN,12,1,4,4,NaN,20,4,20,19,NaN,4,2994,2989
top,NaN,José Maria,Vendedor,CL001,Loja Matriz,NaN,Aspirador de pó,Casa,"88,9","189,9",NaN,"0,05",09/07/2019 16:05,09/12/2019 10:12
freq,NaN,280,3000,793,793,NaN,173,907,173,316,NaN,49,2,2
mean,1.234567e+08,NaN,NaN,NaN,NaN,10010.468667,NaN,NaN,NaN,NaN,2.453333,NaN,NaN,NaN
std,3.489977e+02,NaN,NaN,NaN,NaN,5.772590,NaN,NaN,NaN,NaN,1.107955,NaN,NaN,NaN
min,1.234561e+08,NaN,NaN,NaN,NaN,10001.000000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,NaN
25%,1.234563e+08,NaN,NaN,NaN,NaN,10006.000000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,NaN
50%,1.234567e+08,NaN,NaN,NaN,NaN,10011.000000,NaN,NaN,NaN,NaN,2.000000,NaN,NaN,NaN
75%,1.234570e+08,NaN,NaN,NaN,NaN,10015.000000,NaN,NaN,NaN,NaN,3.000000,NaN,NaN,NaN
max,1.234571e+08,NaN,NaN,NaN,NaN,10020.000000,NaN,NaN,NaN,NaN,4.000000,NaN,NaN,NaN

In [15]:
df_vendas.shape
linhas = df_vendas.shape[0]

In [14]:
# linhas vazias / missing values

df_vendas.isnull().sum()

matricula_funcionario       0
Nome Funcionario            0
Cargo                       0
codigo_loja                 0
nome_loja                   0
codigo_produto              0
descricao_produto           0
Categoria                   0
preco_custo                 0
valor_unitario              0
quantidade                  0
comissao                 2841
dt_venda                    0
dt_entrega                  0
dtype: int64

In [16]:
# valores unicos
#nunique e unique

df_vendas.nunique()

matricula_funcionario      12
Nome Funcionario           12
Cargo                       1
codigo_loja                 4
nome_loja                   4
codigo_produto             20
descricao_produto          20
Categoria                   4
preco_custo                20
valor_unitario             19
quantidade                  4
comissao                    4
dt_venda                 2994
dt_entrega               2989
dtype: int64

In [17]:
df_vendas['Nome Funcionario'].unique()

array(['José Maria', 'Maria das Graças', 'Jorge Mateus', 'Marta Cury',
       'Ricardo Lemos', 'Reginaldo Sodré', 'Felipe Marinho',
       'Marcos Coelho', 'Rita Sampaio', 'Mário Henrique', 'Pamela Lima',
       'Victor Hugo'], dtype=object)